### ISSUE TITLE
Run git repo cleaner on this repository

### ISSUE THREAD

**Issue by jimhester** [hadley/neiss#1]
Currently a freshly cloned repository from this repo is ~392 MB, mainly due to xlsx files which are no longer in the current directory tree and old versions of the serialized injuries.rda files.

``` text
dee2931a333ed2aaf91f5d4f05f2ba0c42a678e7 46381209 NEISS-data-2009-updated-12MAY2015.xlsx
5b5f5f605826abfba89477cb87b88c16c786ff4f 50433719 NEISS-data-2010-updated-12MAY2015.xlsx
9e01b490beb2a3202e0c67d7d8e7b615f0e25af6 52384700 NEISS-data-2011-updated-12MAY2015.xlsx
ddfc9c363b7c4deefaa48659875ede98fba6ab2d 52841138 NEISS-data-2012-updated-12MAY2015.xlsx
3fa687550c3c2009494a152332425bd13c256853 50545095 NEISS-data-2013-updated-12MAY2015.xlsx
a3dccb483707f7e22f87e4da3b29ca66104ea62b 47095154 NEISS-data-2014-updated-12MAY2015.xlsx
41bddad22808d28264c76458d7a32c380ff3d9ae 60184438 injuries.rda
4233863651642c07b6152918f22ca0f160713c68 60213411 injuries.rda
```

You can use the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to strip out references which only occur in the history. It preserves any files which exist in the current HEAD, so you can be sure it won't delete something needed.

Doing this took the size of the `.git` folder from a fresh clone of this repo from 392 MB to 60 MB, so it is a substantial savings.

I just ran the following code from within the `neiss` checkout.

```
java -jar ~/Downloads/bfg-1.12.8.jar --strip-blobs-bigger-than 10M .
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

Then you will have to `git push --force` to update the GitHub repo. This should make cloning this repository much faster (an major issue until this package in on CRAN).

**Comment by hadley** [comment]
Done - thanks!
