### ISSUE TITLE
Bug Report: One data source is missing.

### ISSUE THREAD

**Issue by JiaxiangBU** [hadley/neiss#8]
Hi, @hadley  I just learn the tutorial, [Happy R Users Purrr by Charlotte Wickham](https://github.com/rstudio/rstudio-conf/tree/master/2017/Happy_R_Users_Purrr-Charlotte_Wickham).
At page 58, there is a data file to be downloaded here, 

![image](https://user-images.githubusercontent.com/15884785/55369981-681a0080-552b-11e9-9c1e-d34cdba89e65.png)

But I don't find it in the package neiss.

![image](https://user-images.githubusercontent.com/15884785/55369915-20937480-552b-11e9-9a31-ce01113c3e30.png)

Would you like to tell me where I can get it?

**Comment by hadley** [comment]
I have no recollection of that data set, sorry.
